### PR TITLE
[#773] Add linting for missing clause in try

### LINKED ISSUE #773: Warn about usage of block `try` without `catch`
It could be helpful to get warning when using `try` without `catch`. Because in that case `try` works simply as `do`:
```
user=> (try
  #_=>   (/ 1 0))
Execution error (ArithmeticException) at user/eval6793 (REPL:2).
Divide by zero
```

### PR DESCRIPTION
**Pull request by abogoyavlensky**
Request adds linting for cases when try is used without any clause `catch` or `finally`.

Linting diff:
```
(missing-clause-in-try ✓) clj-kondo script/diff
Linting and writing output to /tmp/clj-kondo-diff/branch.txt
Cloning into 'clj-kondo'...
remote: Enumerating objects: 69, done.
remote: Counting objects: 100% (69/69), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 7214 (delta 23), reused 43 (delta 11), pack-reused 7145
Receiving objects: 100% (7214/7214), 8.03 MiB | 1.28 MiB/s, done.
Resolving deltas: 100% (4153/4153), done.
Linting and writing output to /tmp/clj-kondo-diff/master.txt
198d197
< cljs/closure.clj:1969:3: warning: Missing catch or finally in try
1941c1940
< linting took 10927ms, errors: 395, warnings: 1545
---
> linting took 10207ms, errors: 395, warnings: 1544
```

Resolves #773

### CODE REVIEW

File: src/clj_kondo/impl/linters.clj [hunk 1]
```diff
@@ -191,6 +191,21 @@
                    (str ns-name "/" fn-name)
                    (some? const-true))))))))
 
+(defn- lint-missing-clause-in-try
+  [call]
+  (when (utils/one-of (:name call) [try try+])
```
Comment (abogoyavlensky) [inline src/clj_kondo/impl/linters.clj:196]: Should we include [slingshot's](https://github.com/scgilardi/slingshot) version `try+` for linting? I added it for now cause it seems that version is widely used too.

Comment (borkdude) [reply src/clj_kondo/impl/linters.clj:196]: I'd prefer if we left it out for now. People can use `:lint-as` if they want to lint `clojure.core/try` as `foo.bar/try+`.

File: src/clj_kondo/impl/linters.clj [hunk 2]
```diff
@@ -191,6 +191,21 @@
...
+    (let [clauses #{'catch 'finally}
+          tokens (->> (get-in call [:expr :children])
```
Comment (borkdude) [inline src/clj_kondo/impl/linters.clj:198]: I'd prefer it if we could do the linting here:

https://github.com/borkdude/clj-kondo/blob/846bdb9a4f5f2b39bb6e96c6b3a7f3a4c9afcd0c/src/clj_kondo/impl/analyzer.clj#L824

We already walk the forms over there and have all the information that is needed to create the warnings. This avoids having to walk the AST twice.

File: src/clj_kondo/impl/linters.clj (hunk 1 above)
Comment (abogoyavlensky) [reply src/clj_kondo/impl/linters.clj]: Sure, removed it.

File: src/clj_kondo/impl/linters.clj (hunk 2 above)
Comment (abogoyavlensky) [reply src/clj_kondo/impl/linters.clj]: I moved the linter to `analyze-try` check it please.

**Comment by borkdude** [comment]
Excellent, thank you!
